/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controle.Controle;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author airan.nascimento
 */
public class jfmTela extends javax.swing.JFrame {
    private final Controle c = new Controle();
    private int vez = 0;

    /**
     * Creates new form jfmTela
     * @throws java.io.IOException
     */
    public jfmTela() throws IOException {
        initComponents();
        this.setLocationRelativeTo(this); // Centraliza a tela
        inicializar();
    }
    
    private void inicializar() throws IOException {
        c.carregarArquivo();
        vez = 1;
        lblVitoriasJogador1.setText(c.getVitoriasJogador1()+"");
        lblVitoriasJogador2.setText(c.getVitoriasJogador2()+"");
        lblJogadorNaVez.setText("Jogador " + vez);
        btnJogarNovamente.setEnabled(false);
        desabilitarBotoesJogo();
    }
    
    private void resetarJogo() {
        resetarTextoBotoesJogo();
        habilitarBotoesJogo();
        c.resetarMatriz();
        vez = c.passarVez(vez);
        
        if (vez == 1) {
            lblJogadorNaVez.setText("Jogador 1");
        } else {
            lblJogadorNaVez.setText("Jogador 2");
        }
    }
    
    private void resetarTextoBotoesJogo() {
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        btn9.setText("");
        lblVencedor.setText("");
    }
    
    private void habilitarBotoesJogo() {
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
    }
    
    private void desabilitarBotoesJogo() {
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblJogadorNaVez = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblVitoriasJogador1 = new javax.swing.JLabel();
        lblVitoriasJogador2 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnJogarNovamente = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnResetarScores = new javax.swing.JButton();
        lblVencedor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblTitulo.setText("TIC - TAC - TOE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblTitulo)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setText("Jogador 1 = X");

        jLabel2.setText("Jogador 2 = O");

        jLabel3.setText("Na vez:");

        jLabel4.setText("Vitórias:");

        jLabel5.setText("Vitórias:");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnJogarNovamente.setText("Jogar Novamente");
        btnJogarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarNovamenteActionPerformed(evt);
            }
        });

        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnResetarScores.setText("Resetar Scores");
        btnResetarScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarScoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblJogadorNaVez)))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVencedor)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblVitoriasJogador2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblVitoriasJogador1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(18, 18, 18)
                        .addComponent(btnJogarNovamente)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair))
                    .addComponent(btnResetarScores))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(lblVitoriasJogador1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(lblVitoriasJogador2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblJogadorNaVez)
                            .addComponent(lblVencedor))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnResetarScores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(btnJogarNovamente)
                            .addComponent(btnStart))))
                .addContainerGap())
        );

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        habilitarBotoesJogo();
        btnJogarNovamente.setEnabled(true);
        btnStart.setEnabled(false);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnJogarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarNovamenteActionPerformed
        resetarJogo();
    }//GEN-LAST:event_btnJogarNovamenteActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnResetarScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarScoresActionPerformed
        c.resetarVitorias();
        lblVitoriasJogador1.setText(String.valueOf(c.getVitoriasJogador1()));
        lblVitoriasJogador2.setText(String.valueOf(c.getVitoriasJogador2()));
        
        try {
            c.salvarArquivo();
        } catch (IOException ex) {
            Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnResetarScoresActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (vez == 1) {
            btn1.setText("X");
            btn1.setEnabled(false);
            c.substituirCaractere('X', 0, 0);
        } else {
            btn1.setText("O");
            btn1.setEnabled(false);
            c.substituirCaractere('O', 0, 0);
        }
        
        if (c.verificarVencedor(vez) != 0) {
            try {
                c.contabilizarVitoria(vez);
            } catch (IOException ex) {
                Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lblVencedor.setText("Jogador " + vez + " venceu!");
            lblVitoriasJogador1.setText(c.getVitoriasJogador1()+"");
            lblVitoriasJogador2.setText(c.getVitoriasJogador2()+"");
            desabilitarBotoesJogo();
        } else {
            if (c.verificarEmpate(vez)) {
                lblVencedor.setText("Empate!");
            } else {
                vez = c.passarVez(vez);
                lblJogadorNaVez.setText("Jogador " + vez);
            }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (vez == 1) {
            btn2.setText("X");
            btn2.setEnabled(false);
            c.substituirCaractere('X', 0, 1);
        } else {
            btn2.setText("O");
            btn2.setEnabled(false);
            c.substituirCaractere('O', 0, 1);
        }
        
        if (c.verificarVencedor(vez) != 0) {
            try {
                c.contabilizarVitoria(vez);
            } catch (IOException ex) {
                Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lblVencedor.setText("Jogador " + vez + " venceu!");
            lblVitoriasJogador1.setText(c.getVitoriasJogador1()+"");
            lblVitoriasJogador2.setText(c.getVitoriasJogador2()+"");
            desabilitarBotoesJogo();
        } else {
            if (c.verificarEmpate(vez)) {
                lblVencedor.setText("Empate!");
            } else {
                vez = c.passarVez(vez);
                lblJogadorNaVez.setText("Jogador " + vez);
            }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (vez == 1) {
            btn3.setText("X");
            btn3.setEnabled(false);
            c.substituirCaractere('X', 0, 2);
        } else {
            btn3.setText("O");
            btn3.setEnabled(false);
            c.substituirCaractere('O', 0, 2);
        }
        
        if (c.verificarVencedor(vez) != 0) {
            try {
                c.contabilizarVitoria(vez);
            } catch (IOException ex) {
                Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lblVencedor.setText("Jogador " + vez + " venceu!");
            lblVitoriasJogador1.setText(c.getVitoriasJogador1()+"");
            lblVitoriasJogador2.setText(c.getVitoriasJogador2()+"");
            desabilitarBotoesJogo();
        } else {
            if (c.verificarEmpate(vez)) {
                lblVencedor.setText("Empate!");
            } else {
                vez = c.passarVez(vez);
                lblJogadorNaVez.setText("Jogador " + vez);
            }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (vez == 1) {
            btn4.setText("X");
            btn4.setEnabled(false);
            c.substituirCaractere('X', 1, 0);
        } else {
            btn4.setText("O");
            btn4.setEnabled(false);
            c.substituirCaractere('O', 1, 0);
        }
        
        if (c.verificarVencedor(vez) != 0) {
            try {
                c.contabilizarVitoria(vez);
            } catch (IOException ex) {
                Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lblVencedor.setText("Jogador " + vez + " venceu!");
            lblVitoriasJogador1.setText(c.getVitoriasJogador1()+"");
            lblVitoriasJogador2.setText(c.getVitoriasJogador2()+"");
            desabilitarBotoesJogo();
        } else {
            if (c.verificarEmpate(vez)) {
                lblVencedor.setText("Empate!");
            } else {
                vez = c.passarVez(vez);
                lblJogadorNaVez.setText("Jogador " + vez);
            }
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (vez == 1) {
            btn5.setText("X");
            btn5.setEnabled(false);
            c.substituirCaractere('X', 1, 1);
        } else {
            btn5.setText("O");
            btn5.setEnabled(false);
            c.substituirCaractere('O', 1, 1);
        }
        
        if (c.verificarVencedor(vez) != 0) {
            try {
                c.contabilizarVitoria(vez);
            } catch (IOException ex) {
                Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lblVencedor.setText("Jogador " + vez + " venceu!");
            lblVitoriasJogador1.setText(c.getVitoriasJogador1()+"");
            lblVitoriasJogador2.setText(c.getVitoriasJogador2()+"");
            desabilitarBotoesJogo();
        } else {
            if (c.verificarEmpate(vez)) {
                lblVencedor.setText("Empate!");
            } else {
                vez = c.passarVez(vez);
                lblJogadorNaVez.setText("Jogador " + vez);
            }
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (vez == 1) {
            btn6.setText("X");
            btn6.setEnabled(false);
            c.substituirCaractere('X', 1, 2);
        } else {
            btn6.setText("O");
            btn6.setEnabled(false);
            c.substituirCaractere('O', 1, 2);
        }
        
        if (c.verificarVencedor(vez) != 0) {
            try {
                c.contabilizarVitoria(vez);
            } catch (IOException ex) {
                Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lblVencedor.setText("Jogador " + vez + " venceu!");
            lblVitoriasJogador1.setText(c.getVitoriasJogador1()+"");
            lblVitoriasJogador2.setText(c.getVitoriasJogador2()+"");
            desabilitarBotoesJogo();
        } else {
            if (c.verificarEmpate(vez)) {
                lblVencedor.setText("Empate!");
            } else {
                vez = c.passarVez(vez);
                lblJogadorNaVez.setText("Jogador " + vez);
            }
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (vez == 1) {
            btn7.setText("X");
            btn7.setEnabled(false);
            c.substituirCaractere('X', 2, 0);
        } else {
            btn7.setText("O");
            btn7.setEnabled(false);
            c.substituirCaractere('O', 2, 0);
        }
        
        if (c.verificarVencedor(vez) != 0) {
            try {
                c.contabilizarVitoria(vez);
            } catch (IOException ex) {
                Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lblVencedor.setText("Jogador " + vez + " venceu!");
            lblVitoriasJogador1.setText(c.getVitoriasJogador1()+"");
            lblVitoriasJogador2.setText(c.getVitoriasJogador2()+"");
            desabilitarBotoesJogo();
        } else {
            if (c.verificarEmpate(vez)) {
                lblVencedor.setText("Empate!");
            } else {
                vez = c.passarVez(vez);
                lblJogadorNaVez.setText("Jogador " + vez);
            }
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (vez == 1) {
            btn8.setText("X");
            btn8.setEnabled(false);
            c.substituirCaractere('X', 2, 1);
        } else {
            btn8.setText("O");
            btn8.setEnabled(false);
            c.substituirCaractere('O', 2, 1);
        }
        
        if (c.verificarVencedor(vez) != 0) {
            try {
                c.contabilizarVitoria(vez);
            } catch (IOException ex) {
                Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lblVencedor.setText("Jogador " + vez + " venceu!");
            lblVitoriasJogador1.setText(c.getVitoriasJogador1()+"");
            lblVitoriasJogador2.setText(c.getVitoriasJogador2()+"");
            desabilitarBotoesJogo();
        } else {
            if (c.verificarEmpate(vez)) {
                lblVencedor.setText("Empate!");
            } else {
                vez = c.passarVez(vez);
                lblJogadorNaVez.setText("Jogador " + vez);
            }
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (vez == 1) {
            btn9.setText("X");
            btn9.setEnabled(false);
            c.substituirCaractere('X', 2, 2);
        } else {
            btn9.setText("O");
            btn9.setEnabled(false);
            c.substituirCaractere('O', 2, 2);
        }
        
        if (c.verificarVencedor(vez) != 0) {
            try {
                c.contabilizarVitoria(vez);
            } catch (IOException ex) {
                Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            lblVencedor.setText("Jogador " + vez + " venceu!");
            lblVitoriasJogador1.setText(c.getVitoriasJogador1()+"");
            lblVitoriasJogador2.setText(c.getVitoriasJogador2()+"");
            desabilitarBotoesJogo();
        } else {
            if (c.verificarEmpate(vez)) {
                lblVencedor.setText("Empate!");
            } else {
                vez = c.passarVez(vez);
                lblJogadorNaVez.setText("Jogador " + vez);
            }
        }
    }//GEN-LAST:event_btn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jfmTela().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(jfmTela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnJogarNovamente;
    private javax.swing.JButton btnResetarScores;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblJogadorNaVez;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVencedor;
    private javax.swing.JLabel lblVitoriasJogador1;
    private javax.swing.JLabel lblVitoriasJogador2;
    // End of variables declaration//GEN-END:variables
}
